modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="sgcraft"
version="2.2.1"
displayName="SGCraft"
authors="OscarC16"
description="Stargate Mod for NeoForge"

[[dependencies.sgcraft]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sgcraft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
